sudo: true                  # Required to install packages

env:
  DOCKER_COMPOSE_VERSION: 1.5.1

language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - cp src/main/resources/travis.application.conf src/main/resources/application.conf
  - ./acceptance-tests.sh

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email:
    - team-pathfinder@zalando.de