# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.11.7
jdk:
  - oraclejdk8

notifications:
  email:
    - team-spearheads@zalando.de