# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION it:test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.11.7
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE ROLE innkeepertest superuser login createdb;' -U postgres
  - psql -c 'CREATE DATABASE innkeepertest;' -U postgres

notifications:
  email:
    - team-spearheads@zalando.de