# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

services:
  - docker

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'CREATE ROLE innkeepertest superuser login createdb;' -U postgres
  - psql -c 'CREATE DATABASE innkeepertest;' -U postgres

script:
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - cp src/main/resources/travis.application.conf src/main/resources/application.conf
  - ./acceptance-tests.sh

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

notifications:
  email:
    - team-pathfinder@zalando.de